### PR TITLE
Release/v1.0.0

### PR DESCRIPTION
**Pull request by santidrj**

### CODE REVIEW

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- server.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES-My-Pet-Care-Web/pullRequest?prid=5650007&bid=18500213)

**Review by xavier-campos-diaz — DISMISSED** [review]

**Review by AlbertPG — DISMISSED** [review]
Okey

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- server.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES-My-Pet-Care-Web/pullRequest?prid=5650007&bid=18500213)

**Review by marclll — DISMISSED** [review]

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- server.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES-My-Pet-Care-Web/pullRequest?prid=5650007&bid=18500213)

**Review by xavier-campos-diaz — APPROVED** [review]

**Review by marclll — APPROVED** [review]

**Review by AlbertPG — APPROVED** [review]
Okey

**Pull request merged**
